# Generated by Django 4.0.5 on 2022-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
