# Generated by Django 4.0.5 on 2022-08-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupby', '0003_remove_post_image_remove_post_image_title_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_title',
        ),
    ]
