# Generated by Django 4.0.5 on 2022-08-16 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groupby', '0004_remove_image_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='recruit_conference_video',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='short_from_video',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='short_introduce',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='startup_culture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='startup_introduce',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='startup_welfare',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='startup_name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupby.post')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recruiting', models.BooleanField(default=False)),
                ('recruit_ending', models.DateField(default=datetime.date.today)),
                ('recruit_position', models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('app', 'app')], max_length=200)),
                ('techstack', models.CharField(choices=[('django', 'django'), ('react', 'react'), ('python', 'python')], max_length=200)),
                ('career', models.TextField(null=True)),
                ('job_info', models.TextField(null=True)),
                ('qualification', models.TextField(null=True)),
                ('preference', models.TextField(null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupby.post')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('introduce', models.TextField(null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupby.post')),
            ],
        ),
    ]
