# Generated by Django 4.0.5 on 2022-08-16 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groupby', '0005_remove_post_content_post_recruit_conference_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='recruit_ending',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
