# Generated by Django 4.0.5 on 2022-08-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupby', '0006_alter_post_create_date_alter_recruit_recruit_ending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short_from_video',
            new_name='short_form_video',
        ),
        migrations.AlterField(
            model_name='recruit',
            name='recruit_position',
            field=models.CharField(choices=[('front-end', 'front-end'), ('back-end', 'back-end'), ('app', 'app')], max_length=200),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='techstack',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('react', 'react')], max_length=200),
        ),
    ]
