# Generated by Django 4.0.3 on 2022-08-29 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupby', '0011_alter_recruit_is_recruiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('briefIntro', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('pitch', models.URLField(blank=True, null=True)),
                ('culture', models.TextField(blank=True, null=True)),
                ('benefit', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='groupby.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('career', models.CharField(blank=True, max_length=700, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='groupby.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupPosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('preferred', models.TextField(blank=True, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('task', models.TextField(blank=True, null=True)),
                ('careerType', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='groupby.careertype')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='groupby.position')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='groupby.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupPt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pts', to='groupby.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tags', to='groupby.startup')),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Recruit',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='startupposition',
            name='techStacks',
            field=models.ManyToManyField(related_name='startupPositions', to='groupby.techstack'),
        ),
    ]
