# Generated by Django 4.0.3 on 2022-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupby', '0012_careertype_position_startup_startupimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='startupimage',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
    ]
